# Задание 0 

Используя материал занятия, документацию по библиотеке Pandas и набор данных <a href='https://www.kaggle.com/gregorut/videogamesales'>Video Game Sales</a>.

In [ ]:
import pandas as pd
vgsales = pd.read_csv('https://gist.githubusercontent.com/Danil42Russia/0a69528ab4a2133220234187aba83199/raw/2ed49d49c0c6a139b370fc1f4eb2db43a330b030/vgsales.csv')

# Задание 1

Вывести все доступные платформы, на которых выпускалась хотя-бы одна игра.

In [ ]:
print(vgsales['Platform'].unique())

['Wii' 'NES' 'GB' 'DS' 'X360' 'PS3' 'PS2' 'SNES' 'GBA' '3DS' 'PS4' 'N64'
 'PS' 'XB' 'PC' '2600' 'PSP' 'XOne' 'GC' 'WiiU' 'GEN' 'DC' 'PSV' 'SAT'
 'SCD' 'WS' 'NG' 'TG16' '3DO' 'GG' 'PCFX']

# Задание 2

Добавить к копии набора данных столбец '**metacritic_rating**' и заполнить его данными из набора данных <a href='https://www.kaggle.com/skateddu/metacritic-all-time-games-stats'>Metacritic all time games stats</a>.

In [ ]:
metacritic = pd.read_csv('https://gist.githubusercontent.com/Danil42Russia/0a69528ab4a2133220234187aba83199/raw/2ed49d49c0c6a139b370fc1f4eb2db43a330b030/metacritic_games.csv')

Оставляем только нужные столбцы, чтобы при объединении не добавлять лишних данных.

Для объединения оставляем колонки: '**name**' и '**platform**'. Для дополнительного набора данных оставляем '**rating**'.

In [ ]:
metacritic = metacritic[['name', 'platform', 'rating']]

В данных наборах данных, имена колонок имеют разные имена и разные регистры. Что-бы не усложнять объединение перемеименовываем колонки.

In [ ]:
metacritic = metacritic.rename(columns={'name': 'Name', 'platform': 'Platform', 'rating': 'metacritic_rating'})

В двух наборах данных, значения для описания платформы имеют разные названия. 

Что-бы при объединение осталось больше данных, меняем названия платформ из набора <a href='https://www.kaggle.com/skateddu/metacritic-all-time-games-stats'>Metacritic all time games stats</a> на <a href='https://www.kaggle.com/gregorut/videogamesales'>Video Game Sales</a>.

In [ ]:
values_mapper = {
    'WII':    'Wii',
    'WIIU':   'WiiU',
    'XONE':   'XOne',
    'XBOX':   'XB',
    'VITA':   'PSV',
    'Switch': 'NS',
}

metacritic = metacritic.replace({'Platform': values_mapper})

Из-за различия в названиях игр в наборах данных сделаем небольшую хитрость.

Уберём все пробельные и пунктуационные символы их названий игр и добавим нормализованные название в отдельную колонку '**Normalized_Name**'.

In [ ]:
import string
def normalized_name(name: str) -> str:
    return name.lower().translate({ord(c): None for c in string.whitespace + string.punctuation})

In [ ]:
vgsales['Normalized_Name'] = vgsales.apply(lambda row : normalized_name(row['Name']), axis = 1)

Названия игр из набора данных <a href='https://www.kaggle.com/skateddu/metacritic-all-time-games-stats'>Metacritic all time games stats</a> для нас не важны, то уберём их.

In [ ]:
metacritic['Normalized_Name'] = metacritic.apply(lambda row : normalized_name(row['Name']), axis = 1)
metacritic = metacritic.drop('Name', axis=1)

Мерджим значения.

В качестве колонок для пересечения выбрано '**Normalized_Name**' и '**Platform**', потому что одна игра может выйти сразу на нескольких платформах.

In [ ]:
data = pd.merge(vgsales, metacritic, how='inner', on=['Normalized_Name', 'Platform'])
data = data.drop('Normalized_Name', axis=1)

data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,metacritic_rating
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,E
1,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,E
2,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,E
3,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01,E
4,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02,E
...,...,...,...,...,...,...,...,...,...,...,...,...
8489,16582,PGA European Tour,N64,2000.0,Sports,Infogrames,0.01,0.00,0.00,0.00,0.01,E
8490,16585,Planet Monsters,GBA,2001.0,Action,Titus,0.01,0.00,0.00,0.00,0.01,E
8491,16587,Bust-A-Move 3000,GC,2003.0,Puzzle,Ubisoft,0.01,0.00,0.00,0.00,0.01,E
8492,16588,Breach,PC,2011.0,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01,T
8493,16591,Mega Brain Boost,DS,2008.0,Puzzle,Majesco Entertainment,0.01,0.00,0.00,0.00,0.01,E

# Задание 3

Вывести список игр, рейтинг которых равен '**M**' и год издания не ранее 2012 года

In [ ]:
rating_games = data[(data['metacritic_rating'] == 'M') & (data['Year'] >= 2012)]

In [ ]:
rating_games

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,metacritic_rating
10,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40,M
13,24,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38,M
19,35,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.88,0.65,2.52,14.03,M
20,36,Call of Duty: Black Ops II,X360,2012.0,Shooter,Activision,8.25,4.30,0.07,1.12,13.73,M
29,45,Grand Theft Auto V,PS4,2014.0,Action,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98,M
...,...,...,...,...,...,...,...,...,...,...,...,...
8391,16178,Republique,PS4,2016.0,Action,Nippon Ichi Software,0.00,0.01,0.01,0.00,0.01,M
8402,16225,Carmageddon: Max Damage,XOne,2016.0,Action,Stainless Games,0.01,0.01,0.00,0.00,0.01,M
8432,16336,Chaos;Child,PS4,2015.0,Adventure,5pb,0.00,0.00,0.01,0.00,0.01,M
8453,16402,The Technomancer,PC,2016.0,Role-Playing,Focus Home Interactive,0.00,0.01,0.00,0.00,0.01,M
8482,16556,Bound By Flame,X360,2014.0,Role-Playing,NaN,0.00,0.01,0.00,0.00,0.01,M

# Задание 4

Рассчитать и вывести описательные статистики для списка, полученного в пункте 3

Статистика продаж в зависимости от жанра на платформе '**PC**'

In [ ]:
globals_sales_pc = rating_games[rating_games['Platform'] == 'PC'][['Genre', 'Global_Sales']].groupby(by=['Genre']).sum()

globals_sales_pc

              Global_Sales
Genre
Action                7.64
Adventure             0.26
Fighting              0.05
Role-Playing         11.05
Shooter              11.91
Strategy              1.08

Самый продавоемый жанр на '**PC**'

In [ ]:
globals_sales_pc[globals_sales_pc['Global_Sales'] == globals_sales_pc['Global_Sales'].max()]

         Global_Sales
Genre
Shooter         11.91

Самый не продавоемый жанр на '**PC**'

In [ ]:
globals_sales_pc[globals_sales_pc['Global_Sales'] == globals_sales_pc['Global_Sales'].min()]

          Global_Sales
Genre
Fighting          0.05

Средняя медианная выпуска игр в зависимости от платформы

In [ ]:
rating_games[['Year', 'Platform']].groupby(by=['Platform']).median()

            Year
Platform
3DS       2013.0
PC        2014.0
PS3       2013.0
PS4       2015.0
PSV       2014.0
WiiU      2013.0
X360      2012.0
XOne      2015.0

Средняя медианная продаж игр в зависимости от платформы в разных регионах

In [ ]:
rating_games[['NA_Sales',	'EU_Sales',	'JP_Sales',	'Other_Sales', 'Platform']].groupby(by=['Platform']).median()

          NA_Sales  EU_Sales  JP_Sales  Other_Sales
Platform
3DS          0.090     0.010      0.12         0.01
PC           0.070     0.100      0.00         0.02
PS3          0.230     0.200      0.04         0.09
PS4          0.350     0.410      0.05         0.15
PSV          0.090     0.050      0.05         0.04
WiiU         0.075     0.075      0.00         0.01
X360         0.310     0.160      0.01         0.04
XOne         0.430     0.280      0.00         0.07

Средняя медианная продаж игр в зависимости от жанров в разных регионах

In [ ]:
rating_games[['NA_Sales',	'EU_Sales',	'JP_Sales',	'Other_Sales', 'Genre']].groupby(by=['Genre']).median()

              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre
Action           0.145     0.135     0.010        0.040
Adventure        0.030     0.030     0.010        0.010
Fighting         0.115     0.060     0.010        0.010
Misc             0.135     0.070     0.015        0.060
Role-Playing     0.100     0.080     0.000        0.030
Shooter          0.250     0.245     0.000        0.070
Simulation       0.175     0.060     0.050        0.035
Strategy         0.250     0.250     0.000        0.075

# Задание 5

Вывести жанры игр с количеством игр, которые принадлежат соответствующему жанру в виде '**<жанр> - <количество игр>**' для всех жанров, которые содержат в своем названии не менее 3 различных гласных

Функция для проверки, что текст содержит в своем названии не менее 3 различных гласных.

In [ ]:
def is_right_name(word: str) -> bool:
    vowels = ['a', 'e', 'i', 'u', 'y', 'o']
    word = word.lower()

    vowels_in_word = {letter for letter in list(word) if letter in vowels}

    return len(vowels_in_word) >= 3

Оставляем только те игры, у которых в названии три уникальных гласных букв.

In [ ]:
unique_games = data[data['Name'].apply(lambda x: is_right_name(x))]

Группируем игры по жанрам и считаем количество игр в данном жанре. Сортируем по количеству игр в данном жанре от большего к меньшему.

In [ ]:
unique_games = unique_games.groupby('Genre').size().reset_index(name='Count').sort_values('Count', ascending=False)

Выводим жанры игр с количеством игр

In [ ]:
print((unique_games['Genre'].map(str) + ' - ' + unique_games['Count'].map(str)).to_string(index=False))

     Action - 1686
     Shooter - 814
      Sports - 732
Role-Playing - 671
      Racing - 565
        Misc - 495
    Platform - 454
    Fighting - 370
   Adventure - 297
  Simulation - 293
    Strategy - 279
      Puzzle - 202